class CfgPatches
{
	class weap_StreetYou_optic3
	{
		requiredversion=1;
		units[]={};
	};
};
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class CfgWeapons
{
	class WeaponSlotsInfo;
	class SlotInfo;
	class Rifle_Base_F;
	class ItemCore;
	class InventoryItem_Base_F;
	class InventoryMuzzleItem_Base_F;
	class InventoryOpticsItem_Base_F;
	class muzzle_snds_H;
	class muzzle_snds_L;
	class muzzle_snds_M;
	class muzzle_snds_B;
	class muzzle_snds_H_MG;
	class optic_Hamr;
	class optic_Arco;
	class optic_Aco;
	class optic_SOS;
	class optic_Yorris;
	class optic_DMS;
	class NVGoggles;
	class NVGoggles_OPFOR;
	class optic_str_nit: ItemCore
	{
		scope=2;
		author="AbsolutSoft";
		displayName="$STR_nit_name";
		picture="\wpn_optic3\nit\nitb";
		model="\wpn_optic3\nit\nit.p3d";
		descriptionShort="$STR_nit_desc";
		weaponInfoType="RscWeaponZeroing";
		inertia=0;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=6;
			modelOptics="\A3\Weapons_F\empty";
			optics=1;
			class OpticsModes
			{
				class kobra
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.5;
					memoryPointCamera="eye";
					discreteDistance[]={100,200,300};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=300;
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_rak_kro: optic_DMS
	{
		scope=2;
		author="Alex-I/Street-you";
		displayName="$STR_racou_kro_name";
		picture="\wpn_optic3\rakurs\raou.paa";
		model="\wpn_optic3\rakurs\raku_pl";
		descriptionShort="$STR_racou_kro_desc";
		weaponInfoType="RscWeaponZeroing";
		inertia=0.1;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=8;
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					discreteDistance[]={200};
					discreteDistanceInitIndex=0;
					distanceZoomMin=200;
					distanceZoomMax=200;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.048;
					opticsZoomMax=0.055;
					opticsZoomInit=0.050000001;
					discreteDistance[]={300,400};
					discreteDistanceInitIndex=0;
					distanceZoomMin=400;
					distanceZoomMax=500;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\rakurs\data\scope_ou"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
			};
		};
	};
	class optic_str_rakurs: optic_str_rak_kro
	{
		displayName="$STR_racou_name";
		author="Alex-I/Street-you";
		picture="\wpn_optic3\rakurs\ra_ou.paa";
		model="\wpn_optic3\rakurs\rakurs";
		descriptionShort="$STR_racou_kro_desc";
	};
	class optic_str_cod2: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_cod_name";
		picture="\wpn_optic3\cod2\cod2.paa";
		model="\wpn_optic3\cod2\cod2";
		descriptionShort="$STR_cod_desc";
		weaponInfoType="RscWeaponZeroing";
		inertia=0.1;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=8;
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
				class Snip2
				{
					opticsID=2;
					useModelOptics=0;
					opticsPPEffects[]=
					{
						""
					};
					opticsZoomMin=0.050000001;
					opticsZoomMax=0.071000002;
					opticsZoomInit=0.055;
					discreteDistance[]={300};
					discreteDistanceInitIndex=0;
					distanceZoomMin=300;
					distanceZoomMax=300;
					memoryPointCamera="vieweye";
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
			};
		};
	};
	class optic_str_cod2_kro: optic_str_cod2
	{
		displayName="$STR_cod_kro_name";
		author="Street-you";
		picture="\wpn_optic3\cod2\cod2Kro.paa";
		model="\wpn_optic3\cod2\cod2_pl";
		descriptionShort="$STR_cod_desc";
		weaponInfoType="RscWeaponZeroing";
	};
	class optic_str_psu: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_PSU_name";
		picture="\wpn_optic3\psu\psu.paa";
		model="\wpn_optic3\psu\psu";
		descriptionShort="$STR_PSU_desc";
		weaponInfoType="RscWeaponZeroing";
		inertia=0.1;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=8;
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.15000001;
					memoryPointCamera="eye";
					discreteDistance[]={300};
					discreteDistanceInitIndex=0;
					distanceZoomMin=300;
					distanceZoomMax=300;
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
				class Snip2
				{
					opticsID=2;
					useModelOptics=0;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.046;
					opticsZoomMax=0.063000001;
					opticsZoomInit=0.050000001;
					discreteDistance[]={300};
					discreteDistanceInitIndex=0;
					distanceZoomMin=300;
					distanceZoomMax=300;
					memoryPointCamera="vieweye";
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
			};
		};
	};
	class optic_str_psu_kro: optic_str_psu
	{
		displayName="$STR_PSU_kro_name";
		author="Street-you";
		picture="\wpn_optic3\psu\psuK.paa";
		model="\wpn_optic3\psu\psu_pl";
		descriptionShort="$STR_PSU_desc";
	};
	class optic_str_p1x42: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_pi_name";
		picture="\wpn_optic3\pilad\pilad.paa";
		model="\wpn_optic3\pilad\p142";
		descriptionShort="$STR_pi_desc";
		weaponInfoType="RscWeaponZeroing";
		inertia=0;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=4;
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					discreteDistance[]={200};
					discreteDistanceInitIndex=0;
					distanceZoomMin=200;
					distanceZoomMax=200;
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_p1x42_kro: optic_str_p1x42
	{
		displayName="$STR_pi_kro_name";
		author="Street-you";
		picture="\wpn_optic3\pilad\piladK.paa";
		model="\wpn_optic3\pilad\p142_pl";
		descriptionShort="$STR_pi_desc";
	};
	class optic_str_ded5_20: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_ded5L_name";
		picture="\wpn_optic3\dedal_5-20\ded.paa";
		model="\wpn_optic3\dedal_5-20\ded_201";
		descriptionShort="$STR_ded5L_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=12;
			weaponInfoType="RscWeaponRangeZeroing";
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={300,400,500,600,650,700,750,800,850,900,950,1000,1050,1200,1250,1300,1350,1400,1450,1500,1550,1600,1650,1700,1750,1800,1850,1900,1950,2000,2050,2100,2150,2200,2250};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=2250;
					discretefov[]={0.050000001,0.025,0.0167,0.0125};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\dedal_5-20\data\ret\scope_5k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_10k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_15k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_20k"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_ded5_20Drob: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_ded5Drob_name";
		picture="\wpn_optic3\dedal_5-20\ded.paa";
		model="\wpn_optic3\dedal_5-20\ded_201";
		descriptionShort="$STR_ded5Drob_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=12;
			weaponInfoType="RscWeaponRangeZeroing";
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={100,150};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=150;
					discretefov[]={0.050000001,0.025,0.0167,0.0125};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\dedal_5-20\data\ret\scope_5k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_10k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_15k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_20k"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_ded5_20_kro: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_ded5L_kro_name";
		picture="\wpn_optic3\dedal_5-20\ded_kro.paa";
		model="\wpn_optic3\dedal_5-20\ded_201_pl";
		descriptionShort="$STR_ded5L_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=12;
			weaponInfoType="RscWeaponRangeZeroing";
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={300,400,500,600,650,700,750,800,850,900,950,1000,1050,1200,1250,1300,1350,1400,1450,1500,1550,1600,1650,1700,1750,1800,1850,1900,1950,2000,2050,2100,2150,2200,2250};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=2250;
					discretefov[]={0.050000001,0.025,0.0167,0.0125};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\dedal_5-20\data\ret\scope_5k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_10k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_15k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_20k"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_ded5_20Drob_kro: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_ded5Drob_kro_name";
		picture="\wpn_optic3\dedal_5-20\ded_kro.paa";
		model="\wpn_optic3\dedal_5-20\ded_201_pl";
		descriptionShort="$STR_ded5Drob_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=12;
			weaponInfoType="RscWeaponRangeZeroing";
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={100,150};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=150;
					discretefov[]={0.050000001,0.025,0.0167,0.0125};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\dedal_5-20\data\ret\scope_5k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_10k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_15k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_20k"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_ded5_20n: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_ded5nL_name";
		picture="\wpn_optic3\dedal_5-20\ded_n.paa";
		model="\wpn_optic3\dedal_5-20\ded_201n";
		descriptionShort="$STR_ded5nL_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=16;
			weaponInfoType="RscWeaponRangeZeroing";
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={300,400,500,600,650,700,750,800,850,900,950,1000,1050,1200,1250,1300,1350,1400,1450,1500,1550,1600,1650,1700,1750,1800,1850,1900,1950,2000,2050,2100,2150,2200,2250};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=2250;
					discretefov[]={0.050000001,0.025,0.0167,0.0125};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\dedal_5-20\data\ret\scope_5k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_10k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_15k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_20k"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_ded5_20nDrob: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_ded5nDrob_name";
		picture="\wpn_optic3\dedal_5-20\ded_n.paa";
		model="\wpn_optic3\dedal_5-20\ded_201n";
		descriptionShort="$STR_ded5nDrob_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=16;
			weaponInfoType="RscWeaponRangeZeroing";
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={100,150};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=150;
					discretefov[]={0.050000001,0.025,0.0167,0.0125};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\dedal_5-20\data\ret\scope_5k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_10k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_15k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_20k"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_ded5_20n_kro: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_ded5nL_kro_name";
		picture="\wpn_optic3\dedal_5-20\ded_kro_n.paa";
		model="\wpn_optic3\dedal_5-20\ded_201n_pl";
		descriptionShort="$STR_ded5nL_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=16;
			weaponInfoType="RscWeaponRangeZeroing";
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={300,400,500,600,650,700,750,800,850,900,950,1000,1050,1200,1250,1300,1350,1400,1450,1500,1550,1600,1650,1700,1750,1800,1850,1900,1950,2000,2050,2100,2150,2200,2250};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=2250;
					discretefov[]={0.050000001,0.025,0.0167,0.0125};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\dedal_5-20\data\ret\scope_5k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_10k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_15k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_20k"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_ded5_20nDrob_kro: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_ded5nDrob_kro_name";
		picture="\wpn_optic3\dedal_5-20\ded_kro_n.paa";
		model="\wpn_optic3\dedal_5-20\ded_201n_pl";
		descriptionShort="$STR_ded5nDrob_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=16;
			weaponInfoType="RscWeaponRangeZeroing";
			optics=1;
			modelOptics="\A3\Weapons_F\empty";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={100,150};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=150;
					discretefov[]={0.050000001,0.025,0.0167,0.0125};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"\wpn_optic3\dedal_5-20\data\ret\scope_5k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_10k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_15k",
						"\wpn_optic3\dedal_5-20\data\ret\scope_20k"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_NFx52: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_nfL_name";
		picture="\wpn_optic3\NF\nf.paa";
		model="\wpn_optic3\NF\nfx521";
		descriptionShort="$STR_nfL_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=12;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={300,400,500,600,650,700,750,800,850,900,950,1000,1050,1100,1150,1200,1250,1300,1350,1400,1450,1500,1550,1600,1650,1700,1750,1800,1850,1900,1950,2000,2050,2100,2150,2200,2250};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=2250;
					discretefov[]={0.0167,0.0099999998,0.00715,0.0055499999,0.0045349998};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"wpn_optic3\NF\data\ret\scope_NF15",
						"wpn_optic3\NF\data\ret\scope_NF25",
						"wpn_optic3\NF\data\ret\scope_NF35",
						"wpn_optic3\NF\data\ret\scope_NF45",
						"wpn_optic3\NF\data\ret\scope_NF55"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_NFx52Drob: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_nfDrob_name";
		picture="\wpn_optic3\NF\nf.paa";
		model="\wpn_optic3\NF\nfx521";
		descriptionShort="$STR_nfDrob_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=12;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={100,150};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=150;
					discretefov[]={0.0167,0.0099999998,0.00715,0.0055499999,0.0045349998};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"wpn_optic3\NF\data\ret\scope_NF15",
						"wpn_optic3\NF\data\ret\scope_NF25",
						"wpn_optic3\NF\data\ret\scope_NF35",
						"wpn_optic3\NF\data\ret\scope_NF45",
						"wpn_optic3\NF\data\ret\scope_NF55"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_NFx52_kro: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_nfL_kro_name";
		picture="\wpn_optic3\NF\nf_kro.paa";
		model="\wpn_optic3\NF\nfx521_pl";
		descriptionShort="$STR_nfL_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=12;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={300,400,500,600,650,700,750,800,850,900,950,1000,1050,1100,1150,1200,1250,1300,1350,1400,1450,1500,1550,1600,1650,1700,1750,1800,1850,1900,1950,2000,2050,2100,2150,2200,2250};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=2250;
					discretefov[]={0.0167,0.0099999998,0.00715,0.0055499999,0.0045349998};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"wpn_optic3\NF\data\ret\scope_NF15",
						"wpn_optic3\NF\data\ret\scope_NF25",
						"wpn_optic3\NF\data\ret\scope_NF35",
						"wpn_optic3\NF\data\ret\scope_NF45",
						"wpn_optic3\NF\data\ret\scope_NF55"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_NFx52Drob_kro: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_nfDrob_kro_name";
		picture="\wpn_optic3\NF\nf_kro.paa";
		model="\wpn_optic3\NF\nfx521_pl";
		descriptionShort="$STR_nfDrob_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=12;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={100,150};
					discreteDistanceInitIndex=1;
					distanceZoomMin=100;
					distanceZoomMax=150;
					discretefov[]={0.0167,0.0099999998,0.00715,0.0055499999,0.0045349998};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"wpn_optic3\NF\data\ret\scope_NF15",
						"wpn_optic3\NF\data\ret\scope_NF25",
						"wpn_optic3\NF\data\ret\scope_NF35",
						"wpn_optic3\NF\data\ret\scope_NF45",
						"wpn_optic3\NF\data\ret\scope_NF55"
					};
					visionMode[]=
					{
						"Normal"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_NFx52n: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_nfnL_name";
		picture="\wpn_optic3\NF\nf_n.paa";
		model="\wpn_optic3\NF\nfx521n";
		descriptionShort="$STR_nfnL_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=16;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={300,400,500,600,650,700,750,800,850,900,950,1000,1050,1100,1150,1200,1250,1300,1350,1400,1450,1500,1550,1600,1650,1700,1750,1800,1850,1900,1950,2000,2050,2100,2150,2200,2250};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=2250;
					discretefov[]={0.0167,0.0099999998,0.00715,0.0055499999,0.0045349998};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"wpn_optic3\NF\data\ret\scope_NF15",
						"wpn_optic3\NF\data\ret\scope_NF25",
						"wpn_optic3\NF\data\ret\scope_NF35",
						"wpn_optic3\NF\data\ret\scope_NF45",
						"wpn_optic3\NF\data\ret\scope_NF55"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_NFx52nDrob: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_nfnDrob_name";
		picture="\wpn_optic3\NF\nf_n.paa";
		model="\wpn_optic3\NF\nfx521n";
		descriptionShort="$STR_nfnDrob_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=16;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={100,150};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=150;
					discretefov[]={0.0167,0.0099999998,0.00715,0.0055499999,0.0045349998};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"wpn_optic3\NF\data\ret\scope_NF15",
						"wpn_optic3\NF\data\ret\scope_NF25",
						"wpn_optic3\NF\data\ret\scope_NF35",
						"wpn_optic3\NF\data\ret\scope_NF45",
						"wpn_optic3\NF\data\ret\scope_NF55"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_NFx52n_kro: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_nfnL_kro_name";
		picture="\wpn_optic3\NF\nf_kro_n.paa";
		model="\wpn_optic3\NF\nfx521n_pl";
		descriptionShort="$STR_nfnL_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=16;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={300,400,500,600,650,700,750,800,850,900,950,1000,1050,1100,1150,1200,1250,1300,1350,1400,1450,1500,1550,1600,1650,1700,1750,1800,1850,1900,1950,2000,2050,2100,2150,2200,2250};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=2250;
					discretefov[]={0.0167,0.0099999998,0.00715,0.0055499999,0.0045349998};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"wpn_optic3\NF\data\ret\scope_NF15",
						"wpn_optic3\NF\data\ret\scope_NF25",
						"wpn_optic3\NF\data\ret\scope_NF35",
						"wpn_optic3\NF\data\ret\scope_NF45",
						"wpn_optic3\NF\data\ret\scope_NF55"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
	class optic_str_NFx52nDrob_kro: optic_DMS
	{
		scope=2;
		author="Street-you";
		displayName="$STR_nfnDrob_kro_name";
		picture="\wpn_optic3\NF\nf_kro_n.paa";
		model="\wpn_optic3\NF\nfx521n_pl";
		descriptionShort="$STR_nfnDrob_desc";
		inertia=0.2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			opticType=2;
			mass=16;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=2;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.1;
					opticsZoomMax=0.25;
					opticsZoomInit=0.125;
					discreteDistance[]={100,150};
					discreteDistanceInitIndex=1;
					distanceZoomMin=100;
					distanceZoomMax=150;
					discretefov[]={0.0167,0.0099999998,0.00715,0.0055499999,0.0045349998};
					discreteInitIndex=0;
					memoryPointCamera="eye";
					modelOptics[]=
					{
						"wpn_optic3\NF\data\ret\scope_NF15",
						"wpn_optic3\NF\data\ret\scope_NF25",
						"wpn_optic3\NF\data\ret\scope_NF35",
						"wpn_optic3\NF\data\ret\scope_NF45",
						"wpn_optic3\NF\data\ret\scope_NF55"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Snip2
				{
					opticsID=1;
					useModelOptics=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="vieweye";
					discreteDistance[]={100};
					discreteDistanceInitIndex=0;
					distanceZoomMin=100;
					distanceZoomMax=100;
					opticsFlare=0;
					opticsDisablePeripherialVision=1;
					cameraDir="";
					visionMode[]={};
					opticsPPEffects[]=
					{
						""
					};
				};
			};
		};
	};
};
class cfgMods
{
	author="76561198086111011";
	timepacked="1455918123";
};
