class CfgPatches
{
	class weap_StreetYou_droboviki
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
	};
};
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class single_close_optics1;
class single_medium_optics1;
class single_far_optics1;
class single_far_optics2;
class fullauto_medium;
class SlotInfo;
class ItemCore;
class InventoryItem_Base_F;
class InventoryMuzzleItem_Base_F;
class InventoryOpticsItem_Base_F;
class CowsSlot;
class PointerSlot;
class MuzzleSlot;
class asdg_OptR_drob_dvtl_str;
class asdg_OptR_drob_str;
class asdg_str_SideW;
class cfgRecoils
{
	recoil_doublebarrel[]=
	{
		0,
		0,
		0,
		0.039999999,
		"0.036943*(1)",
		"0.0134348*(4)",
		0.090000004,
		"0.019755*(1)",
		"0.003056*(4)",
		0.12,
		0,
		0,
		0.18000001,
		"-0.003138*(1)",
		"-0.0005*(4)",
		0.12,
		"-0.001177*(1)",
		"-0.000188*(4)",
		0.12,
		0,
		0
	};
	recoil_doublebarrel_double[]=
	{
		0,
		0,
		0,
		0.050000001,
		"0.036943*(1.5)",
		"0.0134348*(8)",
		0.090000004,
		"0.019755*(1.5)",
		"0.003056*(8)",
		0.12,
		0,
		0,
		0.18000001,
		"-0.003138*(1.5)",
		"-0.0005*(8)",
		0.12,
		"-0.001177*(1.5)",
		"-0.000188*(8)",
		0.12,
		0,
		0
	};
	recoil_doublebarrel_prone[]=
	{
		0,
		0,
		0,
		0.039999999,
		"0.036943*(0.5)",
		"0.0134348*(3)",
		0.090000004,
		"0.019755*(0.5)",
		"0.003056*(3)",
		0.12,
		0,
		0,
		0.18000001,
		"-0.003138*(0.5)",
		"-0.0005*(3)",
		0.12,
		"-0.001177*(0.5)",
		"-0.000188*(3)",
		0.12,
		0,
		0
	};
};
class CfgWeapons
{
	class arifle_SDAR_F;
	class srifle_DMR_01_F;
	class srifle_LRR_F;
	class launch_O_Titan_F;
	class LMG_Mk200_F;
	class srifle_EBR_F;
	class hgun_P07_F;
	class str_toz194: srifle_EBR_F
	{
		author="New World Interactive";
		displayname="$STR_toz194_name";
		descriptionshort="$STR_toz194_desc";
		model="wpn_r_f2\toz194\toz194.p3d";
		picture="\wpn_r_f2\toz194\gear_toz194_x_ca";
		reloadAction="GestureReloadM4SSAS";
		discreteDistance[]={50,75};
		maxZeroing=100;
		recoil="recoil_ebr";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\wpn_r_f_anm\benelli.rtm"
		};
		drySound[]=
		{
			"wpn_r_f_snd\ak545\empty.ogg",
			1,
			1,
			20
		};
		magazines[]=
		{
			"7pul_drob",
			"7pul_pula"
		};
		reloadMagazineSound[]=
		{
			"wpn_r_f_snd\12calibr\reload.ogg",
			1.3,
			1,
			30
		};
		class GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		modes[]=
		{
			"Single",
			"far_optic1",
			"medium_optic2",
			"far_optic2"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_01",
					0.39810717,
					1.2,
					30
				};
				closure2[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_02",
					0.39810717,
					1,
					30
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\1.wav",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\1.wav",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\1.wav",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\1.wav",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_forest",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_houses",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_interior",
							1.9952624,
							1,
							2200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_meadows",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_trees",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.82999998;
			dispersion=0.0049999999;
			recoil="recoil_single_ebr";
			recoilProne="recoil_single_prone_ebr";
			minRange=0;
			minRangeProbab=0.40000001;
			midRange=55;
			midRangeProbab=0.60000002;
			maxRange=90;
			maxRangeProbab=0.1;
			distanceZoomMin=5;
			distanceZoomMax=120;
		};
		class far_optic1: Single
		{
			showToPlayer=0;
			minRange=0;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.69999999;
			maxRange=100;
			maxRangeProbab=0.2;
			aiRateOfFire=5;
			aiRateOfFireDistance=100;
			requiredOpticType=1;
		};
		class medium_optic2: Single
		{
			showToPlayer=0;
			minRange=5;
			minRangeProbab=0.5;
			midRange=65;
			midRangeProbab=0.89999998;
			maxRange=100;
			maxRangeProbab=0.2;
			aiRateOfFire=6;
			aiRateOfFireDistance=100;
			requiredOpticType=2;
		};
		class far_optic2: far_optic1
		{
			minRange=10;
			minRangeProbab=0.5;
			midRange=70;
			midRangeProbab=0.80000001;
			maxRange=150;
			maxRangeProbab=0.2;
			aiRateOfFire=8;
			aiRateOfFireDistance=150;
			requiredOpticType=2;
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=95;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={-0.050000001,0.34999999};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
			class CowsSlot: asdg_OptR_drob_str
			{
				iconPosition[]={0.75,0.30000001};
				iconScale=0.2;
				access=1;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
		};
	};
	class str_mp133: srifle_EBR_F
	{
		author="$STR_A3_Bohemia_Interactive";
		displayname="$STR_mp133_name";
		descriptionshort="$STR_mp133_desc";
		model="wpn_r_f2\mp133\mp133.p3d";
		picture="\wpn_r_f2\mp133\gear_mp133_x_ca";
		reloadAction="GestureReloadM4SSAS";
		discreteDistance[]={50,75};
		maxZeroing=100;
		recoil="recoil_ebr";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\wpn_r_f_anm\a2\M24.rtm"
		};
		drySound[]=
		{
			"wpn_r_f_snd\ak545\empty.ogg",
			1,
			1,
			20
		};
		magazines[]=
		{
			"7pul_drob",
			"7pul_pula"
		};
		reloadMagazineSound[]=
		{
			"wpn_r_f_snd\12calibr\reload.ogg",
			1.3,
			1,
			30
		};
		class GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		modes[]=
		{
			"Single"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_01",
					0.39810717,
					1.2,
					30
				};
				closure2[]=
				{
					"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_02",
					0.39810717,
					1,
					30
				};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\1.wav",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\1.wav",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\1.wav",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\1.wav",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_forest",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_houses",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_interior",
							1.9952624,
							1,
							2200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_meadows",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_trees",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.82999998;
			dispersion=0.0049999999;
			recoil="recoil_single_ebr";
			recoilProne="recoil_single_prone_ebr";
			minRange=0;
			minRangeProbab=0.40000001;
			midRange=55;
			midRangeProbab=0.60000002;
			maxRange=90;
			maxRangeProbab=0.1;
			distanceZoomMin=1;
			distanceZoomMax=100;
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=95;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={-0.079999998,0.38499999};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
		};
	};
	class str_mp133k: str_mp133
	{
		author="Bohemia_Interactive\Street-you";
		displayname="$STR_mp133k_name";
		descriptionshort="$STR_mp133k_desc";
		model="wpn_r_f2\mp133\mp133k.p3d";
		picture="\wpn_r_f2\mp133\gear_mp133_x_ca";
		magazines[]=
		{
			"5drob_mp133k",
			"5pul_mp133k"
		};
		reloadAction="GestureReloadEBR";
		reloadMagazineSound[]=
		{
			"A3\sounds_f\weapons\reloads\new_ebr",
			0.63095701,
			1,
			35
		};
	};
	class str_saiga12_isp3: srifle_EBR_F
	{
		author="[PROTOTYPE]";
		displayname="$STR_s12_isp3_name";
		descriptionshort="$STR_s12_isp3_desc";
		model="wpn_r_f2\saiga12\s1.p3d";
		picture="\wpn_r_f2\saiga12\gear_s1_x_ca";
		reloadAction="iHLC_GestureReloadAK12";
		discreteDistance[]={50,75};
		maxZeroing=100;
		recoil="recoil_ebr";
		handanim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F\Rifles\MX\data\Anim\MX_afg.rtm"
		};
		drySound[]=
		{
			"wpn_r_f_snd\ak545\empty.ogg",
			1,
			1,
			20
		};
		magazines[]=
		{
			"5pul_s1_drob",
			"3pul_s1_drob",
			"3pul_s1_pula",
			"5pul_s1_pula"
		};
		reloadMagazineSound[]=
		{
			"wpn_r_f_snd\12calibr\saiga_reload",
			1.3,
			1,
			30
		};
		class GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		modes[]=
		{
			"Single"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				class BaseSoundModeType
				{
					closure1[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_01",
						0.39810717,
						1.2,
						30
					};
					closure2[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_02",
						0.39810717,
						1,
						30
					};
					soundClosure[]=
					{
						"closure1",
						0.5,
						"closure2",
						0.5
					};
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_forest",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_houses",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_interior",
							1.9952624,
							1,
							2200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_meadows",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_trees",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.1;
			dispersion=0.0049999999;
			recoil="recoil_single_ebr";
			recoilProne="recoil_single_prone_ebr";
			minRange=0;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.60000002;
			maxRange=90;
			maxRangeProbab=0.1;
			distanceZoomMin=1;
			distanceZoomMax=100;
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=95;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={-0.041999999,0.44999999};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
		};
	};
	class str_saiga12c: str_saiga12_isp3
	{
		author="MTindle";
		displayname="$STR_s1_2_name";
		descriptionshort="$STR_s12_isp3_desc";
		model="wpn_r_f2\saiga12\s1_2.p3d";
		picture="\wpn_r_f2\saiga12\ui\gear_s1_2_x_ca";
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=100;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={0,0.37};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
			class CowsSlot: asdg_OptR_drob_dvtl_str
			{
				access=1;
				iconPosition[]={0.60000002,0.28};
				iconScale=0.2;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
		};
	};
	class str_saiga12: str_saiga12_isp3
	{
		author="MTindle\DICE";
		displayname="$STR_s1_3_name";
		descriptionshort="$STR_s12_isp3_desc";
		model="wpn_r_f2\saiga12\s1_3.p3d";
		picture="\wpn_r_f2\saiga12\ui\gear_s1_3_x_ca";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F_Mark\LongRangeRifles\DMR_06\data\Anim\DMR_06.rtm"
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=115;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={0,0.38};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
			class CowsSlot: asdg_OptR_drob_dvtl_str
			{
				access=1;
				iconPosition[]={0.58499998,0.30000001};
				iconScale=0.2;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
		};
	};
	class str_saiga20k: srifle_EBR_F
	{
		author="AbsolutSoft";
		displayname="$STR_s20k_name";
		descriptionshort="$STR_s20k_desc";
		model="wpn_r_f2\saiga12\s2.p3d";
		picture="\wpn_r_f2\saiga12\gear_s2_x_ca";
		reloadAction="iHLC_GestureReloadAK12";
		recoil="recoil_ebr";
		discreteDistance[]={50,75};
		maxZeroing=100;
		handanim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F\Rifles\MX\data\Anim\MX_afg.rtm"
		};
		drySound[]=
		{
			"wpn_r_f_snd\ak545\empty.ogg",
			1,
			1,
			20
		};
		magazines[]=
		{
			"8pul_s2_drob",
			"5pul_s2_drob",
			"5pul_s2_pula",
			"8pul_s2_pula"
		};
		reloadMagazineSound[]=
		{
			"wpn_r_f_snd\12calibr\saiga_reload",
			1.3,
			1,
			30
		};
		class GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		modes[]=
		{
			"Single",
			"far_optic1",
			"medium_optic2",
			"far_optic2"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				class BaseSoundModeType
				{
					closure1[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_01",
						0.39810717,
						1.2,
						30
					};
					closure2[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_02",
						0.39810717,
						1,
						30
					};
					soundClosure[]=
					{
						"closure1",
						0.5,
						"closure2",
						0.5
					};
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\saiga20.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\saiga20.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\saiga20.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\saiga20.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_forest",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_houses",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_interior",
							1.9952624,
							1,
							2200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_meadows",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_trees",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.1;
			dispersion=0.0035000001;
			recoil="recoil_single_ebr";
			recoilProne="recoil_single_prone_ebr";
			minRange=2;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.60000002;
			maxRange=90;
			maxRangeProbab=0.1;
			distanceZoomMin=1;
			distanceZoomMax=90;
		};
		class far_optic1: Single
		{
			showToPlayer=0;
			minRange=0;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.69999999;
			maxRange=100;
			maxRangeProbab=0.2;
			aiRateOfFire=5;
			aiRateOfFireDistance=100;
			requiredOpticType=1;
		};
		class medium_optic2: Single
		{
			showToPlayer=0;
			minRange=5;
			minRangeProbab=0.5;
			midRange=65;
			midRangeProbab=0.89999998;
			maxRange=100;
			maxRangeProbab=0.2;
			aiRateOfFire=6;
			aiRateOfFireDistance=100;
			requiredOpticType=2;
		};
		class far_optic2: far_optic1
		{
			minRange=10;
			minRangeProbab=0.5;
			midRange=70;
			midRangeProbab=0.80000001;
			maxRange=150;
			maxRangeProbab=0.2;
			aiRateOfFire=8;
			aiRateOfFireDistance=150;
			requiredOpticType=2;
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=95;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={0,0.37};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
			class CowsSlot: asdg_OptR_drob_dvtl_str
			{
				access=1;
				iconPosition[]={0.60000002,0.30000001};
				iconScale=0.2;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
		};
	};
	class str_saiga20k2: str_saiga20k
	{
		author="DICE";
		displayname="$STR_s2_2_name";
		descriptionshort="$STR_s20k_desc";
		model="wpn_r_f2\saiga12\s2_2.p3d";
		picture="\wpn_r_f2\saiga12\ui\gear_s2_2_x_ca";
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=90;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={0,0.38999999};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
			class CowsSlot: asdg_OptR_drob_dvtl_str
			{
				access=1;
				iconPosition[]={0.62,0.31999999};
				iconScale=0.2;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
		};
	};
	class str_saiga20: str_saiga20k
	{
		author="DICE";
		displayname="$STR_s2_3_name";
		descriptionshort="$STR_s20k_desc";
		model="wpn_r_f2\saiga12\s2_3.p3d";
		picture="\wpn_r_f2\saiga12\ui\gear_s2_3_x_ca";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F_Mark\LongRangeRifles\DMR_06\data\Anim\DMR_06.rtm"
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=95;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={0,0.38499999};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
			class CowsSlot: asdg_OptR_drob_dvtl_str
			{
				access=1;
				iconPosition[]={0.60000002,0.31999999};
				iconScale=0.2;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
		};
	};
	class str_saiga20s_t: srifle_EBR_F
	{
		author="AbsolutSoft";
		displayname="$STR_s20k_tak_name";
		descriptionshort="$STR_s20k_tak_desc";
		model="wpn_r_f2\saiga12t\s1.p3d";
		picture="\wpn_r_f2\saiga12t\gear_s12_x_ca";
		reloadAction="iHLC_GestureReloadAK12";
		recoil="recoil_ebr";
		discreteDistance[]={100,150};
		maxZeroing=150;
		handanim[]=
		{
			"OFP2_ManSkeleton",
			"\wpn_r_f_anm\str_anim\HaAnm\sa12.rtm"
		};
		drySound[]=
		{
			"wpn_r_f_snd\ak545\empty.ogg",
			1,
			1,
			20
		};
		magazines[]=
		{
			"20pul_s2_drob",
			"20pul_s2_pula"
		};
		reloadMagazineSound[]=
		{
			"wpn_r_f_snd\12calibr\saiga_reload",
			1.3,
			1,
			30
		};
		class GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		modes[]=
		{
			"Single",
			"far_optic1",
			"medium_optic2",
			"far_optic2"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				class BaseSoundModeType
				{
					closure1[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_01",
						0.39810717,
						1.2,
						30
					};
					closure2[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_02",
						0.39810717,
						1,
						30
					};
					soundClosure[]=
					{
						"closure1",
						0.5,
						"closure2",
						0.5
					};
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\saiga20.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\saiga20.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\saiga20.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\saiga20.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_forest",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_houses",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_interior",
							1.9952624,
							1,
							2200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_meadows",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_trees",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.1;
			dispersion=0.0033;
			recoil="recoil_single_ebr";
			recoilProne="recoil_single_prone_ebr";
			minRange=2;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.60000002;
			maxRange=90;
			maxRangeProbab=0.1;
			distanceZoomMin=1;
			distanceZoomMax=90;
		};
		class far_optic1: Single
		{
			showToPlayer=0;
			minRange=0;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.69999999;
			maxRange=100;
			maxRangeProbab=0.2;
			aiRateOfFire=5;
			aiRateOfFireDistance=100;
			requiredOpticType=1;
		};
		class medium_optic2: Single
		{
			showToPlayer=0;
			minRange=5;
			minRangeProbab=0.5;
			midRange=65;
			midRangeProbab=0.89999998;
			maxRange=100;
			maxRangeProbab=0.2;
			aiRateOfFire=6;
			aiRateOfFireDistance=100;
			requiredOpticType=2;
		};
		class far_optic2: far_optic1
		{
			minRange=10;
			minRangeProbab=0.30000001;
			midRange=70;
			midRangeProbab=0.80000001;
			maxRange=150;
			maxRangeProbab=0.40000001;
			aiRateOfFire=8;
			aiRateOfFireDistance=150;
			requiredOpticType=2;
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=120;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={0.1,0.38999999};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
			class CowsSlot: CowsSlot
			{
				iconPosition[]={0.60000002,0.30000001};
				iconScale=0.2;
				access=1;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
			class PointerSlot: asdg_str_SideW
			{
				access=1;
				iconPosition[]={0.5,0.34999999};
				iconScale=0.2;
				linkproxy="\A3\data_f\proxies\weapon_slots\SIDE";
			};
		};
	};
	class str_vepr12: srifle_EBR_F
	{
		author="Mongol";
		displayname="$STR_vepr12_name";
		descriptionshort="$STR_vepr12_desc";
		model="wpn_r_f2\vepr12m\vepr12.p3d";
		picture="\wpn_r_f2\vepr12m\gear_v12_x_ca";
		reloadAction="iHLC_GestureReloadAK12";
		recoil="recoil_ebr";
		discreteDistance[]={100,150};
		maxZeroing=150;
		handanim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F\Rifles\MX\data\Anim\mx.rtm"
		};
		drySound[]=
		{
			"wpn_r_f_snd\ak545\empty.ogg",
			1,
			1,
			20
		};
		magazines[]=
		{
			"20pul_s1_drob",
			"20pul_s1_pula"
		};
		reloadMagazineSound[]=
		{
			"wpn_r_f_snd\12calibr\saiga_reload",
			1.3,
			1,
			30
		};
		class GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		modes[]=
		{
			"Single",
			"far_optic1",
			"medium_optic2",
			"far_optic2"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				class BaseSoundModeType
				{
					closure1[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_01",
						0.39810717,
						1.2,
						30
					};
					closure2[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_02",
						0.39810717,
						1,
						30
					};
					soundClosure[]=
					{
						"closure1",
						0.5,
						"closure2",
						0.5
					};
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_forest",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_houses",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_interior",
							1.9952624,
							1,
							2200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_meadows",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_trees",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.1;
			dispersion=0.0049999999;
			recoil="recoil_single_ebr";
			recoilProne="recoil_single_prone_ebr";
			minRange=2;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.60000002;
			maxRange=90;
			maxRangeProbab=0.1;
			distanceZoomMin=1;
			distanceZoomMax=90;
		};
		class far_optic1: Single
		{
			showToPlayer=0;
			minRange=0;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.69999999;
			maxRange=100;
			maxRangeProbab=0.2;
			aiRateOfFire=5;
			aiRateOfFireDistance=100;
			requiredOpticType=1;
		};
		class medium_optic2: Single
		{
			showToPlayer=0;
			minRange=5;
			minRangeProbab=0.5;
			midRange=65;
			midRangeProbab=0.89999998;
			maxRange=100;
			maxRangeProbab=0.2;
			aiRateOfFire=6;
			aiRateOfFireDistance=100;
			requiredOpticType=2;
		};
		class far_optic2: far_optic1
		{
			minRange=10;
			minRangeProbab=0.30000001;
			midRange=70;
			midRangeProbab=0.80000001;
			maxRange=150;
			maxRangeProbab=0.40000001;
			aiRateOfFire=8;
			aiRateOfFireDistance=150;
			requiredOpticType=2;
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=120;
			class MuzzleSlot: MuzzleSlot
			{
				iconPosition[]={0.050000001,0.38};
				iconScale=0.2;
				linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[]=
				{
					"muzzle_str_salvo"
				};
			};
			class CowsSlot: asdg_OptR_drob_str
			{
				iconPosition[]={0.58999997,0.28999999};
				iconScale=0.2;
				access=1;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
		};
	};
	class str_mc255: srifle_EBR_F
	{
		author="Infinity Ward";
		displayname="$STR_mc_name";
		descriptionshort="$STR_mc_desc";
		model="wpn_r_f2\mc\mtc255.p3d";
		picture="\wpn_r_f2\mc\gear_mc_x_ca";
		reloadAction="ReloadMagazine";
		discreteDistance[]={75,100};
		maxZeroing=100;
		recoil="recoil_ebr";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\wpn_r_f3\izh43\anm\ij.rtm"
		};
		drySound[]=
		{
			"wpn_r_f_snd\ak545\empty.ogg",
			1,
			1,
			20
		};
		magazines[]=
		{
			"5pul_mtc_drob",
			"5pul_mtc_pula"
		};
		reloadMagazineSound[]=
		{
			"wpn_r_f3\izh43\anm\izh43_reloading",
			1.3,
			0.89999998,
			30
		};
		class GunParticles
		{
			class SecondEffect
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		modes[]=
		{
			"Single"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				class BaseSoundModeType
				{
					closure1[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_01",
						0.39810717,
						1.2,
						30
					};
					closure2[]=
					{
						"A3\Sounds_F\arsenal\weapons\LongRangeRifles\DMR_01_Rahim\DMR_01_closure_02",
						0.39810717,
						1,
						30
					};
					soundClosure[]=
					{
						"closure1",
						0.5,
						"closure2",
						0.5
					};
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\saiga12.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_forest",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_houses",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_interior",
							1.9952624,
							1,
							2200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_meadows",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\LongRangeRifles\M320\M320_tail_trees",
							1,
							1,
							2200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin2[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin3[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				begin4[]=
				{
					"wpn_r_f_snd\12calibr\silence.ogg",
					1,
					1,
					2500
				};
				soundBegin[]=
				{
					"begin1",
					0.25,
					"begin2",
					0.25,
					"begin3",
					0.25,
					"begin4",
					0.25
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.1;
			dispersion=0.0049999999;
			recoil="recoil_single_ebr";
			recoilProne="recoil_single_prone_ebr";
			minRange=0;
			minRangeProbab=0.40000001;
			midRange=50;
			midRangeProbab=0.60000002;
			maxRange=90;
			maxRangeProbab=0.1;
			distanceZoomMin=1;
			distanceZoomMax=100;
		};
		class WeaponSlotsInfo
		{
			allowedslots[]={901};
			mass=95;
			class CowsSlot: asdg_OptR_drob_str
			{
				iconPosition[]={0.44999999,0.30000001};
				iconScale=0.2;
				access=1;
				linkproxy="\A3\data_f\proxies\weapon_slots\TOP";
			};
			class PointerSlot: asdg_str_SideW
			{
				access=1;
				iconPosition[]={0.55000001,0.34999999};
				iconScale=0.2;
				linkproxy="\A3\data_f\proxies\weapon_slots\SIDE";
			};
		};
	};
};
class cfgMods
{
	author="76561198086111011";
	timepacked="1455976784";
};
